language: node_js
sudo: false
node_js:
  - "node"
script:
  - npm run-script rimraf
  - npm run-script mkdirp
  - npm run-script compileBabel
  - npm run-script compileUglifyJs
  - npm run-script compilePkg
deploy:
  provider: releases
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: jameswilddev/vnhtml
