sudo: true
dist: trusty
language: node_js
node_js:
  - "node"

jobs:
  include:
    - stage: "@vnhtml/lexer"
      install:
      - npm install --prefix packages/lexer
      script:
      - npm run-script compileBabel --prefix packages/lexer
      - npm run-script compileUglifyJs --prefix packages/lexer
      - npm test --prefix packages/lexer
      deploy:
        - provider: script
          script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/lexer
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
    - stage: "@vnhtml/pretty-printer"
      install:
      - npm install --prefix packages/pretty-printer
      script:
      - npm run-script compileBabel --prefix packages/pretty-printer
      - npm run-script compileUglifyJs --prefix packages/pretty-printer
      - npm test --prefix packages/pretty-printer
      deploy:
        - provider: script
          script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/pretty-printer
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
    - stage: "@vnhtml/parser"
      install:
      - npm install --prefix packages/parser
      script:
      - npm run-script compileBabel --prefix packages/parser
      - npm run-script compileUglifyJs --prefix packages/parser
      - npm test --prefix packages/parser
      deploy:
        - provider: script
          script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/parser
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
    - stage: "@vnhtml/finite-state-machine-generator"
      install:
      - npm install --prefix packages/finite-state-machine-generator
      script:
      - npm run-script compileBabel --prefix packages/finite-state-machine-generator
      - npm run-script compileUglifyJs --prefix packages/finite-state-machine-generator
      - npm test --prefix packages/finite-state-machine-generator
      deploy:
        - provider: script
          script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/finite-state-machine-generator
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
    - stage: "@vnhtml/collector"
      install:
      - npm install --prefix packages/collector
      script:
      - npm run-script compileBabel --prefix packages/collector
      - npm run-script compileUglifyJs --prefix packages/collector
      - npm test --prefix packages/collector
      deploy:
        - provider: script
          script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/collector
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
    - stage: "@vnhtml/html-generator"
      install:
      - npm install --prefix packages/html-generator
      script:
      - npm run-script compileBabel --prefix packages/html-generator
      - npm run-script compileUglifyJs --prefix packages/html-generator
      - npm test --prefix packages/html-generator
      deploy:
        - provider: script
          script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/html-generator
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
    - stage: "@vnhtml/cli"
      before_install:
      - sudo rm /etc/apt/sources.list.d/google-chrome.list
      - sudo dpkg --add-architecture i386
      - sudo apt-get update
      - sudo apt-get install libc6:i386 libstdc++6:i386
      install:
      - npm install --prefix packages/cli
      script:
      - npm run-script rimraf --prefix packages/cli
      - npm run-script mkdirp --prefix packages/cli
      - npm run-script compileBabel --prefix packages/cli
      - npm run-script compileUglifyJs --prefix packages/cli
      - npm run-script compilePkg --prefix packages/cli
      - npm run-script compileZipPkg --prefix packages/cli
      - npm run-script example --prefix packages/cli
      - npm test --prefix packages/cli
      deploy:
        - provider: releases
          api_key:
            secure: knlPUsvTq7Kot60P//i6LsrMxm24wHnOMpxCJ48iTD5YQKPmly++N/lp6FnQb9mSR9a40h9YBOcZwEBDmnUwO25DVKrZ+LEwIGdNeZR82PaNt9M6+O1Ats2tabtjdn7ScSuBRRvxEjJHJ2oeL13+h/W1GN38Rq+esa+Gow4qoTydDY6+Yd3hl4P5qC6UJ5DPej0KUfW6Ot1QWKboPIfEhqxrQyM17yW+3c/a6zBmdZTqw9ujfn/IttNXki8ZRq6odKTDNgoMVnle/qUNZwAUw0BKBrjeHXeCGmmOihDtC+bumLW0xsOSU1fllwzSJ4+Nox/ojyZ8YoD0T3JE8w2zWEOrbWBfEtvj4tNfARuFppNgAjMuYvd/eoBPMa8Niddx5l4VI3ZoTuzXC7W2YZOpNf4IrfOCy5ueYT7884ZcvplV+M0KI6vEPNDsaZez3X8FiuSBzAajXSVZWo/CSl+cjilNOYU8F7AcRDoW3VnRw+w33CBKcCBTjAvPX/E0FlwNkK+FXNgUfSL1f8sh70NpOU7h88Oi0dDC7u1FJWtsXXmfPSB/1APItmDntGE9HuVHtHA7z7k0lMzKsoAhrUllODyy2Sb+//jGnLpCjHmyFEI8C7T0WZHEFM8t3pJ4d77YC0ZHX56PQY6ikfb7mOsa0CbRS04GqL3yY3o0585M6hc=
          file_glob: true
          file: packages/cli/dist/*.zip
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
        - provider: script
          script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/cli
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
env:
  global:
  - secure: iQu+DRNskHnYWuAvfzW9tZAVeusRaVTtvc7lFQkJ4AyLSO/NB+hnRUCkkhx7a6d1ZqiKMNXb8HizcWNSlpHWTYUB9jYgmMgLMdcmg3rjhT3sasz76RCozxLhFi4qKrQSjoiusMlBUzU32hpExiAmXoudhmAhYJyA1qdVBI/fQn0t8J21NDjw93QI9uqvFW3PV6sEkdIXajb5D5bTGffP1CcBZOYuYLIoST8CjvmmqbZTWsXLuFoBxYOmD5g8rHo6dZxE3zKiXHO7qcG7E4dSdrA+e3Pwca63JOOQVCTxc5ArR1ekLVA4EEBIigMcKfjyM/XNb6u40Ra4EGMimhDowN/qphOmdQb7hS9r6MlyEt7WLJIue6JW4BdJLQZXpS+xB2QE1+RcgdVnIhYx8ipd9r/xMV2As68+1pncn7ylnl6Ps1d5cjumFWtBjNO0qkJTapZmqWkd4RtfnGwe0/sh62DNfbMdok3/fTTyNIxeBu5XdeHkOSdfm5RXIjoj3rlHIVOPsuR8UaWNNFcmbvKyAWfKhd3drNFe14vfThUjKL8cY1POZqhPSp7hEhcnwf150eKWU7iy8aVSbR7I2yn6X8R9UfretLh/Lwfe1v0Iep6vuISR+6aNLV4cEEK+d37xY84M4pVQIQjeEoSw3e9MPSYex2bQWYxqs+Euc2RmwVU=
  - secure: L0K2YVdfddKMWPIBT58+elSPvtH4895YW8AKP/9eiG4FM89fdiuO48jHhVmD11xFAJpJhS4lMnQylMz1sgvbK50JlmNdVSzQpCPFjEhZmMuCI8CysWr1SlFLDsXdLcctzZH70T3ZxOn8teItZtI5SEuUZwORD1AtdljtEW6X3O22APjz+HHJxhQynWTX7eCeG/zoYsa9DAONpRNfVFDykPxin9XsZbXAcjKMk10A/N/bzhdbikZ4nDxQlBhbrO0EXSSKfTEr52ovwzLjxgXW2Nvig8g+uwatqBM/nDIpqipgQ4e0AiVgjXM3MIHHERnuChYTAyOJ16q88NVAMh3Pv1w171nxPKuVa9ztgdsZaQJPWytSNIcNxG2SY6f9hlVIfQi+d5849EfrbGDGf1WZ3eDuYG5dOn8BWKS9HVWe3UFtzoOysz5hnfrfkO4SDAlPDFKKP5K7ZIGkoG2rksbdFT6KWgVzOHxje/0AxgsC62mDtxNh5WK7bwtL+P7pHsI5iSxevJc0cgI1WUsTYQg+BeiJdmGFscZu4bK0OVSLZwSFgHmOrEO4X7XlQc/pXD6dTT3oYd1F/43HZ3fkn5oPlaM3liQW/f4zT31ifviM4b28QKZsdAhKndGfg1ijbyGUo9X0KZt0TL+y25x2JbmIhCk2E5X3/JnsKXD+T3Vc1h8=
