sudo: true
dist: trusty
language: node_js
node_js:
  - "node"

jobs:
  include:
    - stage: "@vnhtml/lexer"
      install:
      - npm install --prefix packages/lexer
      script:
      - npm run-script compileBabel --prefix packages/lexer
      - npm run-script compileUglifyJs --prefix packages/lexer
      - cd packages/lexer
      - greenkeeper-lockfile-update
      - npm test
      - greenkeeper-lockfile-upload
      - cd ../..
      deploy:
        - provider: script
          script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/lexer
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
    - stage: "@vnhtml/pretty-printer"
      install:
      - npm install --prefix packages/pretty-printer
      script:
      - npm run-script compileBabel --prefix packages/pretty-printer
      - npm run-script compileUglifyJs --prefix packages/pretty-printer
      - cd packages/pretty-printer
      - greenkeeper-lockfile-update
      - npm test
      - greenkeeper-lockfile-upload
      - cd ../..
      deploy:
        - provider: script
          script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/pretty-printer
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
    - stage: "@vnhtml/parser"
      install:
      - npm install --prefix packages/parser
      script:
      - npm run-script compileBabel --prefix packages/parser
      - npm run-script compileUglifyJs --prefix packages/parser
      - cd packages/parser
      - greenkeeper-lockfile-update
      - npm test
      - greenkeeper-lockfile-upload
      - cd ../..
      deploy:
        - provider: script
          script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/parser
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
    - stage: "@vnhtml/finite-state-machine-generator"
      install:
      - npm install --prefix packages/finite-state-machine-generator
      script:
      - npm run-script compileBabel --prefix packages/finite-state-machine-generator
      - npm run-script compileUglifyJs --prefix packages/finite-state-machine-generator
      - cd packages/finite-state-machine-generator
      - greenkeeper-lockfile-update
      - npm test
      - greenkeeper-lockfile-upload
      - cd ../..
      deploy:
        - provider: script
          script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/finite-state-machine-generator
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
    - stage: "@vnhtml/collector"
      install:
      - npm install --prefix packages/collector
      script:
      - npm run-script compileBabel --prefix packages/collector
      - npm run-script compileUglifyJs --prefix packages/collector
      - cd packages/collector
      - greenkeeper-lockfile-update
      - npm test
      - greenkeeper-lockfile-upload
      - cd ../..
      deploy:
        - provider: script
          script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/collector
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
    - stage: "@vnhtml/html-generator"
      install:
      - npm install --prefix packages/html-generator
      script:
      - npm run-script compileBabel --prefix packages/html-generator
      - npm run-script compileUglifyJs --prefix packages/html-generator
      - cd packages/html-generator
      - greenkeeper-lockfile-update
      - npm test
      - greenkeeper-lockfile-upload
      - cd ../..
      deploy:
        - provider: script
          script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/html-generator
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
    - stage: "@vnhtml/cli"
      before_install:
      - sudo rm /etc/apt/sources.list.d/google-chrome.list
      - sudo dpkg --add-architecture i386
      - sudo apt-get update
      - sudo apt-get install libc6:i386 libstdc++6:i386
      install:
      - npm install --prefix packages/cli
      script:
      - npm run-script rimraf --prefix packages/cli
      - npm run-script mkdirp --prefix packages/cli
      - npm run-script compileBabel --prefix packages/cli
      - npm run-script compileUglifyJs --prefix packages/cli
      - npm run-script compilePkg --prefix packages/cli
      - npm run-script compileZipPkg --prefix packages/cli
      - npm run-script example --prefix packages/cli
      - cd packages/cli
      - greenkeeper-lockfile-update
      - npm test
      - greenkeeper-lockfile-upload
      - cd ../..
      deploy:
        - provider: releases
          api_key:
            secure: Uuexxmz+Q3usIL7Jh067QDCcom3QvlKg4y/6xeGjG7P3bRhAfHfZi35xkxXX+patqUNNziYJR+hCoN5rnfFK+PcJG+c0AYUOewD/KK9eGzHbSKpRsBaqghiH7H5Sk6CNEYb0acAlciXuihElUWgbaYvXWaHVpM2x7v0LLG8PmZrIZm4uHuAcdc2/oQrazshm5S4qFWJzoKfHz/8dvqc9b/J7o9bVlLYZ9KzEdftbNATSCXJFxkNdcrEKuJfP5+M3zE1QwoGhq/pxBRlV2jsfJiyNlTNqgqFfITpwaj4+8x5J5OacGHowGzJRgrr0GrGwXk+Mmn1qFoxyW6aMt5bbVu+WATYW5mRwJI6Et5eHOOU74bwIpkzQ/0Hg6WIqXAGgKSHGHNtERH2MurCE9u7h2+tALveS4qSg6vTRJ216yBtNht23Lmpkrh6e9nccgfmk8sYbVaSbVzI8vcpOdZVcuHZF3I88qpaIYVSttXKQPUx9CScAJ+Td0PqdHi5W7FNkWGFumI4r0IPguqeXY5v8yu2CW42gZ3+5mGs260RUE3ppSXZPtOxQ52H6/jJhlbGEsM5zK/uJrzjQIS3OcbljCTHMpX+BS0KlpEb/2TAlrVfJb+zg8cI/D1YAyYz/rHnfo4Rkj84Va9tN0pDcxBnnQci9qVCxKP1bpS7kLleM0u4=
          file_glob: true
          file: packages/cli/dist/*.zip
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
        - provider: script
          script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/cli
          skip_cleanup: true
          on:
            tags: true
            branch: master
            repo: jameswilddev/vnhtml
env:
  global:
  - secure: nKRrHChe7py9WCGXto136Os6S6rFmEp09p888aSbYkMu0CO+tjgrMJo18v3V5gZbgUvCRfrdiFE31NSk9vzufDTX4Idqr3fHenfsDRfJ4sP1KpQC4sMxjbDqAFpsoNSt6tm6Cz6yn3xHwP4NDpfGYRptJSNT9g8Goa21CbPPys08HXiMKPVgW1X/ZOBl3R1RD9QXXRFyyG6ZuweDtw7N7EY3qzkarxaL7w/H53xUwp/pl9tRc9ch2x5DkHO37eQL6FRu4G0Ma66XGKtHFayt1yUauuml1sCSbMXB9K9gW8eg0PsCl/rjLQCQUQ6EKEi1b40AbgNxx3Jp+PSitg8rcONFUBWWSjclI5AmgoE+hinqIaajVAq3rS/tb654iIwBui1RYSCFQcODk67my3n66N+/SrvpcQpta0RKiXyKXfl5bUXRLwyVnYQtcAcRkRupBd0Wpjdn3Eo58CzOYF7s0Lz63RtCDjfweTh5zQEyBvC649Gx/GVaDH2dQVprTrNja7x6dAz1yGuKXdfOoGpuCSp97AUKr+A5FBXPoyLdKPkYinQLscyU1Hxr8krQ5uZKj86JJPI4Sg65cuSGbDWvDyoJ3sx2StsnsqhJCXflxG5cjSWDmAfvM/bbObnDSjdIJQtEYN9NZdrqT4UQbWTVSQgBsdWTU8+vFZuTZKg1y9k=
  - secure: HFJSw4erg8fwMMzhB27OvX6L3aF1pJJ2my0J11aQ3cUfeUgVGGkroDLw9R9l169lh+aL9mlvm1EcB0n8qpA3GoXSzarU0XAg9eAboKIQywHKov9qwPN4aUTYpmcwsGx6Fx0K+/MHxxx3BkyXMxWGfcKS1TTJJrE0dd/BToErzQ3gHuhwd2CuqMTc2SPBNiL++dukxQonGEf8+olAnH26dqUeXdGJwPIkzxm8N5VUWC6/ULW7kx0PWgkOqaGbZ2FhzzQydOFpEyGRoNwW6jVYPF+dI6aSUbHJbwENCk08Gsot7hXiwHOLuNbGvfkOJI6ch1qSSUoMCjKXHAbtPKQO/JpiF0fhPb+ADEKGHBGunJ73VHR3hupJ1F+zTFudYJSiHlCFYvSFn7oQV2mGR9f+7roj4ajgEYFj4q3irVTxXtPA7Xol4cDJRMlgqFO4GiHrtg6e2VpxRPy0B9jR9M3AdvxW+6Lf57tN22UxDGXJzvoRn/RZ4rPxFBaA1k2Yvr2aKzT6I9BE1gZhdhz2z40yPZCdjI9fXT/OosogLau/0AqTwxUSFX0ECGm0MpQK1hULj5CF1PFUVikP29yW+XQQXuOFqM2FUzVOgjab4XnhlV8s2jJ15W5mmX6kuSbUdg3BIkQIUyzOG8B/8iQXp+qUSYtxoDXftbvn4+bBCdqnDDc=
